version: '3.8'

services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: springresto
      MYSQL_USER: devJPA
      MYSQL_PASSWORD: NBCC1234!
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springresto
      SPRING_DATASOURCE_USERNAME: devJPA
      SPRING_DATASOURCE_PASSWORD: NBCC1234!
    command: ["java", "-jar", "app.jar"]

volumes:
  db_data:
